### ISSUE TITLE
消息头索引注释

### ISSUE THREAD

**Issue by hessonsu** [Leoforgo/ONetworkTalk#2]
/// <summary>
    /// 消息头
    /// Client                startIndex:0,endIndex:1
    /// MessageType    startIndex:2,endIndex:3
    /// MessageID         startIndex:4,endIndex:7
    /// MessageBodyLen startIndex:8,endIndex:11
    /// SourceUserID   startIndex:12,endIndex:19(当用户名最大长度为8)  具体取决于GloblParams.MaxUserLength
    /// DestUserID     startIndex:20,endIndex:27(当用户名最大长度为8)  具体取决于GloblParams.MaxUserLength
    /// </summary>
    public class MessageHeader
你好，以上这个是原先的消息头种注释。
是否应该
    /// Client                startIndex:0,endIndex:1
    /// MessageType    startIndex:1,endIndex:2
    /// MessageID         startIndex:2,endIndex:6
正好可以对应上类文件OFrameDecoder 中的第二个个参数6
以下是OFrameDecoder  中的代码片段
new LengthFieldBasedFrameDecoder(GloblParams.MaxFrameLength, 6, 4, (1 + GloblParams.MaxUserLength) * 2, 0, false);

**Comment by hessonsu** [comment]
new LengthFieldBasedFrameDecoder(GloblParams.MaxFrameLength, 6, 4, (1 + GloblParams.MaxUserLength) * 2, 0, false)；
中的第四个参数 (1 + GloblParams.MaxUserLength) * 2 是对应MessageHeader 中的SourceUserID，DestUserID 2个ID吧？
为什么要+1？

**Comment by Leoforgo** [comment]
你好，是的，这个注释错误了，已修改

不过这个消息头设计现在来看有点缺陷，等后面有时间会修改下

**Comment by hessonsu** [comment]
期待中。。。
